// flow-typed signature: ba94c2a5154bfe6a258b15cf30f135cf
// flow-typed version: <<STUB>>/react-native-lock_vjustinwoo/react-native-lock#feature-customized-theme/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-lock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-lock/auth0-lock' {
  declare module.exports: any;
}

declare module 'react-native-lock/sample-app/app' {
  declare module.exports: any;
}

declare module 'react-native-lock/sample-app/index.android' {
  declare module.exports: any;
}

declare module 'react-native-lock/sample-app/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-lock/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-lock/auth0-lock.js' {
  declare module.exports: $Exports<'react-native-lock/auth0-lock'>;
}
declare module 'react-native-lock/sample-app/app.js' {
  declare module.exports: $Exports<'react-native-lock/sample-app/app'>;
}
declare module 'react-native-lock/sample-app/index.android.js' {
  declare module.exports: $Exports<'react-native-lock/sample-app/index.android'>;
}
declare module 'react-native-lock/sample-app/index.ios.js' {
  declare module.exports: $Exports<'react-native-lock/sample-app/index.ios'>;
}
declare module 'react-native-lock/version.js' {
  declare module.exports: $Exports<'react-native-lock/version'>;
}
