// flow-typed signature: 70f5337c73e7cf47fc53c96a8a1e76d5
// flow-typed version: <<STUB>>/standard-http-error_v^2.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-http-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-http-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-http-error/codes' {
  declare module.exports: any;
}

declare module 'standard-http-error/test/codes_test' {
  declare module.exports: any;
}

declare module 'standard-http-error/test/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-http-error/codes.js' {
  declare module.exports: $Exports<'standard-http-error/codes'>;
}
declare module 'standard-http-error/index' {
  declare module.exports: $Exports<'standard-http-error'>;
}
declare module 'standard-http-error/index.js' {
  declare module.exports: $Exports<'standard-http-error'>;
}
declare module 'standard-http-error/test/codes_test.js' {
  declare module.exports: $Exports<'standard-http-error/test/codes_test'>;
}
declare module 'standard-http-error/test/index_test.js' {
  declare module.exports: $Exports<'standard-http-error/test/index_test'>;
}
